### ISSUE TITLE
Added basic tutorial

### ISSUE THREAD

**Issue by kmitd** [semantic-systems/rdf-star-tutorial#1]
Hi,

It's not much but I've added a basic tutorial (write, query, convert). It assumes usage of GraphDB.

Ilaria

**Comment by RicardoUsbeck** [comment]
Wow, thanks! That was fast. 

@LongquanDoesNLP look :)

**Comment by LongquanJiang** [comment]
@RicardoUsbeck Cool!

**Comment by pchampin** [comment]
Thanks for this first proposal.

Meta-suggestion: rather than committing and opening an issue for discussion, I advise you to make your additions/changes in a branch, and create a pull-request from that branch into `main`. The PR has an integrated discussion, and commenters can also comment specific lines of the PR (even suggest local changes).

Now, a bunch of remarks on the content.

* General: we tend to prefer 'RDF-star' over 'RDF*' to differentiate the current specification from the older version(s) proposed in Olaf's papers. Idem for 'SPARQL-star' vs 'SPARQL*'.

* 'Complex modelling' introduction sentence: I would write "complex relationships" rather than "complex concepts".

* About the running example, I would advise to rename `:man` and `:woman` to more concrete names (e.q. `:alice` and `:bob`). In its current form, the example could be misinterpreted as describing the domain and range of the property `:hasSpouse`.

* 'N-ary relations' example: use lowercase for the instance `:Marriage1`

* 'Named Graphs' example: the example corresponds to no standard syntax. If it was N-Quads, it should not use prefixes. If it was TriG, the pname `:statementId#1` is invalid, and the triples sholud read `:g { :s :p :o }` instead of `:s :p :o :g.`

* 'Expressing data certainty': it is debatable whether the triple should be asserted here, as it is not absolutely certain... NB: I am not saying that it is absolutely wrong to assert it –only that it is a design choice that might bring some confusion. I would advise to remove the asserted triple, and to change 0.9 to 0.4 (to fall into a case were it is clearly safer *not* to assert the triple)

* 'Expressing data value qualifiers': I am not a big fan of using RDF-star for expressing units. For this kind of use-case, I much prefer using a dedicated datatype (e.g. [`cdt:ucum`](https://ci.mines-stetienne.fr/lindt/v2/custom_datatypes.html#ucum)), an intermediary node (`[ rdf:value 32.1; :unit "cm" ]`) or a dedicated property (`:heightInCm 32.1`).

* 'Expressing data value qualifiers' and 'Expressing data provenance': these two examples are typical cases were some intermediary nodes would be a better modelling. Consider this:
```
<< :painting1 :heightInCm 32.1 >>
  :measured [
    :measurementTechnique :laserScanning;
    :measuredOn "2020-02-11"^^xsd:date;
  ],[
    :measurementTechnique :measuringTape;
    :measuredOn "2020-02-12"^^xsd:date;
  ].

<<:man :hasSpouse :woman>>
  :reference [
    :source :theNationalEnquirer;
    :webpage <http://nationalenquirer.com/news/2020-02-12>;
    :retrieved "2020-02-13"^^xsd:dateTime
  ],[
    :source :theNewYotkTime;
    :webpage <http://nytimes.com/news/2020-02-13>;
    :retrieved "2020-02-13"^^xsd:dateTime
  ].
```
Without the intermediary nodes, the information about the different measurements, and the different references, respectively, would be mixed up. See the [dedicated section](https://w3c.github.io/rdf-star/cg-spec/editors_draft.html#the-seminal-example) in the RDF-star specification.

* The SPARQL example with `BIND` is not very compelling, as the value of `?t` is known in advance (so it is not really required in the result...). I suggest to replace it with this
```
PREFIX : <http://example.org/>

SELECT ?t ?p ?o
WHERE {
    <<?man :hasSpouse :woman >> ?p ?o
    BIND(<<:woman :hasSpouse ?man>> as ?t)   
}
```
Here, the generated triple is is not known in advance, and it could not have been produced directly.

* 'Coverting' → 'Converting'

**Comment by RicardoUsbeck** [comment]
See https://github.com/semantic-systems/rdf-star-tutorial/pull/2
